import type { ThaiConsonant } from "./types";

type ConsonantRow = [id: string, letter: string, mnemonic: string];

const rows: ConsonantRow[] = [
  ["01-ko-kai", "ก", "ไก่"],
  ["02-kho-khai", "ข", "ไข่"],
  ["03-kho-khuat", "ฃ", "ขวด"],
  ["04-kho-khwai", "ค", "ควาย"],
  ["05-kho-khon", "ฅ", "คน"],
  ["06-kho-rakhang", "ฆ", "ระฆัง"],
  ["07-ngo-ngu", "ง", "งู"],
  ["08-cho-chan", "จ", "จาน"],
  ["09-cho-ching", "ฉ", "ฉิ่ง"],
  ["10-cho-chang", "ช", "ช้าง"],
  ["11-so-so", "ซ", "โซ่"],
  ["12-cho-choe", "ฌ", "เฌอ"],
  ["13-yo-ying", "ญ", "หญิง"],
  ["14-do-chada", "ฎ", "ชฎา"],
  ["15-to-patak", "ฏ", "ปฏัก"],
  ["16-tho-than", "ฐ", "ฐาน"],
  ["17-tho-montho", "ฑ", "มณโฑ"],
  ["18-tho-phu-thao", "ฒ", "ผู้เฒ่า"],
  ["19-no-nen", "ณ", "เณร"],
  ["20-do-dek", "ด", "เด็ก"],
  ["21-to-tao", "ต", "เต่า"],
  ["22-tho-thung", "ถ", "ถุง"],
  ["23-tho-thahan", "ท", "ทหาร"],
  ["24-tho-thong", "ธ", "ธง"],
  ["25-no-nu", "น", "หนู"],
  ["26-bo-baimai", "บ", "ใบไม้"],
  ["27-po-pla", "ป", "ปลา"],
  ["28-pho-phueng", "ผ", "ผึ้ง"],
  ["29-fo-fa", "ฝ", "ฝา"],
  ["30-pho-phan", "พ", "พาน"],
  ["31-fo-fan", "ฟ", "ฟัน"],
  ["32-pho-samphao", "ภ", "สำเภา"],
  ["33-mo-ma", "ม", "ม้า"],
  ["34-yo-yak", "ย", "ยักษ์"],
  ["35-ro-ruea", "ร", "เรือ"],
  ["36-lo-ling", "ล", "ลิง"],
  ["37-wo-waen", "ว", "แหวน"],
  ["38-so-sala", "ศ", "ศาลา"],
  ["39-so-ruesi", "ษ", "ฤๅษี"],
  ["40-so-suea", "ส", "เสือ"],
  ["41-ho-hip", "ห", "หีบ"],
  ["42-lo-chula", "ฬ", "จุฬา"],
  ["43-o-ang", "อ", "อ่าง"],
  ["44-ho-nokhuk", "ฮ", "นกฮูก"],
];

export const THAI_CONSONANTS: ThaiConsonant[] = rows.map(([id, letter, mnemonic]) => ({
  id,
  letter,
  mnemonic,
  image: `/assets/thai-kingdom/consonants/${id}.webp`,
  audio: `/assets/thai-kingdom/audio/consonants/${id}.wav`,
}));
