import type { CalendarEvent } from "./types";

export const CALENDAR_EVENTS: CalendarEvent[] = [
  // ---- holiday ----
  {
    id: "wai-khru-day",
    title: "วันไหว้ครู",
    category: "holiday",
    occurrence: { kind: "nthWeekday", month: 6, weekday: 4, nth: 1 },
    precision: "approx",
    leadDays: 14,
    note: "แต่ละโรงเรียนกำหนดวันไหว้ครูเองในสัปดาห์แรกๆ ของเดือน มิ.ย. เช็ควันจริงกับปฏิทินโรงเรียน",
    searchTerms: ["พานไหว้ครู", "คำกลอนไหว้ครู", "ดอกไม้ไหว้ครู"],
    contentIdeas: ["ไอเดียพานไหว้ครู", "บทกลอนไหว้ครูพร้อมท่อง", "ป้ายนิเทศวันไหว้ครู"],
  },
  {
    id: "sunthorn-phu-day",
    title: "วันสุนทรภู่",
    category: "holiday",
    occurrence: { kind: "fixed", month: 6, day: 26 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันสุนทรภู่", "ประวัติสุนทรภู่", "พระอภัยมณี", "กลอนสุนทรภู่"],
    contentIdeas: ["ใบงานประวัติสุนทรภู่", "ใบงานระบายสีตัวละครวรรณคดี", "แบบทดสอบวันสุนทรภู่"],
  },
  {
    id: "anti-drugs-day",
    title: "วันต่อต้านยาเสพติดโลก",
    category: "holiday",
    occurrence: { kind: "fixed", month: 6, day: 26 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันต่อต้านยาเสพติด", "คำขวัญวันต่อต้านยาเสพติด"],
    contentIdeas: ["ป้ายนิเทศต่อต้านยาเสพติด", "ใบงานโทษของยาเสพติด"],
  },
  {
    id: "thai-language-day",
    title: "วันภาษาไทยแห่งชาติ",
    category: "holiday",
    occurrence: { kind: "fixed", month: 7, day: 29 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันภาษาไทยแห่งชาติ", "ใบงานภาษาไทย"],
    contentIdeas: ["ใบงานคำราชาศัพท์", "เกมทายคำภาษาไทย", "ป้ายนิเทศวันภาษาไทย"],
  },
  {
    id: "kings-birthday-r10",
    title: "วันเฉลิมพระชนมพรรษา ร.10",
    category: "holiday",
    occurrence: { kind: "fixed", month: 7, day: 28 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันเฉลิมพระชนมพรรษา"],
    contentIdeas: ["ป้ายนิเทศวันเฉลิมพระชนมพรรษา"],
  },
  {
    id: "mothers-day",
    title: "วันแม่แห่งชาติ",
    category: "holiday",
    occurrence: { kind: "fixed", month: 8, day: 12 },
    precision: "exact",
    leadDays: 21,
    searchTerms: ["การ์ดวันแม่", "กลอนวันแม่", "ของขวัญวันแม่ทำเอง"],
    contentIdeas: ["การ์ดวันแม่ให้ระบายสี", "กลอนวันแม่พร้อมท่อง", "ของทำมือให้คุณแม่"],
  },
  {
    id: "science-day",
    title: "วันวิทยาศาสตร์แห่งชาติ",
    category: "holiday",
    occurrence: { kind: "fixed", month: 8, day: 18 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันวิทยาศาสตร์แห่งชาติ", "การทดลองวิทยาศาสตร์ง่ายๆ"],
    contentIdeas: ["ใบงานทดลองวิทยาศาสตร์", "ป้ายนิเทศวันวิทยาศาสตร์"],
  },
  {
    id: "youth-day",
    title: "วันเยาวชนแห่งชาติ",
    category: "holiday",
    occurrence: { kind: "fixed", month: 9, day: 20 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันเยาวชนแห่งชาติ"],
    contentIdeas: ["ป้ายนิเทศวันเยาวชน"],
  },
  {
    id: "chulalongkorn-day",
    title: "วันปิยมหาราช",
    category: "holiday",
    occurrence: { kind: "fixed", month: 10, day: 23 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันปิยมหาราช", "ประวัติรัชกาลที่ 5"],
    contentIdeas: ["ใบงานประวัติรัชกาลที่ 5", "ป้ายนิเทศวันปิยมหาราช"],
  },
  {
    id: "loy-krathong",
    title: "วันลอยกระทง",
    category: "holiday",
    occurrence: { kind: "lookup", key: "loy-krathong" },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["ลอยกระทง", "กระทงประดิษฐ์", "ประวัติลอยกระทง"],
    contentIdeas: ["ใบงานประดิษฐ์กระทง", "ใบงานประวัติลอยกระทง"],
  },
  {
    id: "fathers-day",
    title: "วันพ่อแห่งชาติ",
    category: "holiday",
    occurrence: { kind: "fixed", month: 12, day: 5 },
    precision: "exact",
    leadDays: 21,
    searchTerms: ["การ์ดวันพ่อ", "กลอนวันพ่อ"],
    contentIdeas: ["การ์ดวันพ่อให้ระบายสี", "กลอนวันพ่อพร้อมท่อง"],
  },
  {
    id: "constitution-day",
    title: "วันรัฐธรรมนูญ",
    category: "holiday",
    occurrence: { kind: "fixed", month: 12, day: 10 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันรัฐธรรมนูญ"],
    contentIdeas: ["ป้ายนิเทศวันรัฐธรรมนูญ"],
  },
  {
    id: "new-years-day",
    title: "วันขึ้นปีใหม่",
    category: "holiday",
    occurrence: { kind: "fixed", month: 1, day: 1 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["การ์ดปีใหม่", "กิจกรรมวันปีใหม่"],
    contentIdeas: ["การ์ดอวยพรปีใหม่", "ป้ายนิเทศปีใหม่"],
  },
  {
    id: "childrens-day",
    title: "วันเด็กแห่งชาติ",
    category: "holiday",
    occurrence: { kind: "nthWeekday", month: 1, weekday: 6, nth: 2 },
    precision: "exact",
    leadDays: 21,
    searchTerms: ["คำขวัญวันเด็ก", "กิจกรรมวันเด็ก", "ของรางวัลวันเด็ก"],
    contentIdeas: ["ป้ายคำขวัญวันเด็กปีนี้", "ใบงานกิจกรรมวันเด็ก", "ไอเดียของรางวัลวันเด็ก"],
  },
  {
    id: "teachers-day",
    title: "วันครู",
    category: "holiday",
    occurrence: { kind: "fixed", month: 1, day: 16 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันครู", "คำขวัญวันครู", "คำกลอนวันครู"],
    contentIdeas: ["ป้ายคำขวัญวันครู", "การ์ดอวยพรวันครู"],
  },
  {
    id: "makha-bucha",
    title: "วันมาฆบูชา",
    category: "holiday",
    occurrence: { kind: "lookup", key: "makha-bucha" },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันมาฆบูชา", "ประวัติวันมาฆบูชา"],
    contentIdeas: ["ใบงานวันมาฆบูชา", "ป้ายนิเทศวันมาฆบูชา"],
  },
  {
    id: "valentines-day",
    title: "วันวาเลนไทน์",
    category: "holiday",
    occurrence: { kind: "fixed", month: 2, day: 14 },
    precision: "exact",
    leadDays: 10,
    searchTerms: ["การ์ดวาเลนไทน์", "กิจกรรมวันวาเลนไทน์"],
    contentIdeas: ["การ์ดวาเลนไทน์ให้ระบายสี"],
  },
  {
    id: "womens-day",
    title: "วันสตรีสากล",
    category: "holiday",
    occurrence: { kind: "fixed", month: 3, day: 8 },
    precision: "exact",
    leadDays: 10,
    searchTerms: ["วันสตรีสากล"],
    contentIdeas: ["ป้ายนิเทศวันสตรีสากล"],
  },
  {
    id: "chakri-day",
    title: "วันจักรี",
    category: "holiday",
    occurrence: { kind: "fixed", month: 4, day: 6 },
    precision: "exact",
    leadDays: 10,
    searchTerms: ["วันจักรี", "ประวัติราชวงศ์จักรี"],
    contentIdeas: ["ใบงานประวัติวันจักรี"],
  },
  {
    id: "songkran",
    title: "วันสงกรานต์",
    category: "holiday",
    occurrence: { kind: "range", startMonth: 4, startDay: 13, endMonth: 4, endDay: 15 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["สงกรานต์", "ใบงานสงกรานต์", "ประวัติสงกรานต์"],
    contentIdeas: ["ใบงานประเพณีสงกรานต์", "ป้ายนิเทศวันสงกรานต์"],
  },
  {
    id: "visakha-bucha",
    title: "วันวิสาขบูชา",
    category: "holiday",
    occurrence: { kind: "lookup", key: "visakha-bucha" },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันวิสาขบูชา"],
    contentIdeas: ["ใบงานวันวิสาขบูชา"],
  },
  {
    id: "khao-phansa",
    title: "วันเข้าพรรษา",
    category: "holiday",
    occurrence: { kind: "lookup", key: "khao-phansa" },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["วันเข้าพรรษา", "วันอาสาฬหบูชา"],
    contentIdeas: ["ใบงานวันเข้าพรรษา"],
  },

  // ---- paperwork ----
  {
    id: "dmc-round-1",
    title: "ยืนยันข้อมูลนักเรียน DMC รอบ 1",
    category: "paperwork",
    occurrence: { kind: "fixed", month: 6, day: 10 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["DMC", "ยืนยันข้อมูลนักเรียน", "10 มิถุนายน DMC"],
    contentIdeas: ["คู่มือกรอกข้อมูล DMC", "เช็คลิสต์เอกสารยืนยันตัวตนนักเรียน"],
  },
  {
    id: "dmc-round-2",
    title: "ยืนยันข้อมูลนักเรียน DMC รอบ 2",
    category: "paperwork",
    occurrence: { kind: "fixed", month: 11, day: 10 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["DMC รอบ 2", "10 พฤศจิกายน DMC"],
    contentIdeas: ["คู่มือกรอกข้อมูล DMC รอบ 2"],
  },
  {
    id: "lesson-plan-term-1",
    title: "จัดทำแผนการจัดการเรียนรู้ เทอม 1",
    category: "paperwork",
    occurrence: { kind: "range", startMonth: 5, startDay: 1, endMonth: 5, endDay: 15 },
    precision: "approx",
    leadDays: 14,
    note: "แต่ละโรงเรียนกำหนดกำหนดส่งแผนการสอนไม่ตรงกัน ให้เช็คปฏิทินวิชาการของโรงเรียน",
    searchTerms: ["แผนการจัดการเรียนรู้", "ตัวอย่างแผนการสอน"],
    contentIdeas: ["เทมเพลตแผนการจัดการเรียนรู้", "ตัวอย่างแผนการสอนรายวิชา"],
  },
  {
    id: "lesson-plan-term-2",
    title: "จัดทำแผนการจัดการเรียนรู้ เทอม 2",
    category: "paperwork",
    occurrence: { kind: "range", startMonth: 10, startDay: 15, endMonth: 10, endDay: 31 },
    precision: "approx",
    leadDays: 14,
    note: "แต่ละโรงเรียนกำหนดกำหนดส่งแผนการสอนไม่ตรงกัน ให้เช็คปฏิทินวิชาการของโรงเรียน",
    searchTerms: ["แผนการจัดการเรียนรู้ เทอม 2"],
    contentIdeas: ["เทมเพลตแผนการจัดการเรียนรู้เทอม 2"],
  },
  {
    id: "por-por-5-term-1",
    title: "กรอก ปพ.5 ปลายภาคเรียนที่ 1",
    category: "paperwork",
    occurrence: { kind: "range", startMonth: 9, startDay: 15, endMonth: 10, endDay: 15 },
    precision: "approx",
    leadDays: 14,
    note: "วันปิดภาคเรียนต่างกันในแต่ละโรงเรียน ช่วงนี้เป็นค่าประมาณ",
    searchTerms: ["ปพ.5", "วิธีกรอกปพ.5", "แบบบันทึกผลการเรียน"],
    contentIdeas: ["คู่มือกรอก ปพ.5 ทีละขั้นตอน", "ตัวอย่าง ปพ.5 กรอกแล้ว"],
  },
  {
    id: "por-por-5-term-2",
    title: "กรอก ปพ.5 ปลายภาคเรียนที่ 2",
    category: "paperwork",
    occurrence: { kind: "range", startMonth: 2, startDay: 15, endMonth: 3, endDay: 15 },
    precision: "approx",
    leadDays: 14,
    note: "วันปิดภาคเรียนต่างกันในแต่ละโรงเรียน ช่วงนี้เป็นค่าประมาณ",
    searchTerms: ["ปพ.5 ปลายปี"],
    contentIdeas: ["คู่มือกรอก ปพ.5 ปลายปีการศึกษา"],
  },
  {
    id: "sar-report",
    title: "จัดทำ SAR และประกันคุณภาพภายใน",
    category: "paperwork",
    occurrence: { kind: "range", startMonth: 4, startDay: 1, endMonth: 5, endDay: 15 },
    precision: "approx",
    leadDays: 21,
    note: "กำหนดส่ง SAR จริงขึ้นกับต้นสังกัด เช็คหนังสือแจ้งจาก สพฐ./เขตพื้นที่",
    searchTerms: ["SAR", "รายงานประเมินตนเอง", "ประกันคุณภาพภายในสถานศึกษา"],
    contentIdeas: ["เทมเพลต SAR", "ตัวอย่างรายงานประเมินตนเอง"],
  },

  // ---- evaluation ----
  {
    id: "wpa-agreement",
    title: "จัดทำข้อตกลงพัฒนางาน ว.PA",
    category: "evaluation",
    occurrence: { kind: "range", startMonth: 10, startDay: 1, endMonth: 10, endDay: 31 },
    precision: "approx",
    leadDays: 14,
    note: "ต้นปีงบประมาณ วันจริงขึ้นกับหนังสือแจ้งของ ก.ค.ศ. ในแต่ละปี",
    searchTerms: ["ว.PA", "ข้อตกลงพัฒนางาน", "ตัวอย่าง PA"],
    contentIdeas: ["เทมเพลตข้อตกลง ว.PA", "ตัวอย่างการเขียน ว.PA"],
  },
  {
    id: "wpa-results",
    title: "ส่งผลลัพธ์ ว.PA",
    category: "evaluation",
    occurrence: { kind: "range", startMonth: 9, startDay: 1, endMonth: 9, endDay: 30 },
    precision: "approx",
    leadDays: 14,
    note: "ปลายปีงบประมาณ วันจริงขึ้นกับหนังสือแจ้งของ ก.ค.ศ. ในแต่ละปี",
    searchTerms: ["ผลลัพธ์ ว.PA", "รายงานผล PA"],
    contentIdeas: ["ตัวอย่างรายงานผลลัพธ์ ว.PA"],
  },
  {
    id: "salary-raise-round-1",
    title: "เลื่อนขั้นเงินเดือนรอบ 1",
    category: "evaluation",
    occurrence: { kind: "fixed", month: 4, day: 1 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["เลื่อนขั้นเงินเดือนครู", "แบบประเมินเลื่อนขั้น"],
    contentIdeas: ["คู่มือเตรียมเอกสารเลื่อนขั้นเงินเดือน"],
  },
  {
    id: "salary-raise-round-2",
    title: "เลื่อนขั้นเงินเดือนรอบ 2",
    category: "evaluation",
    occurrence: { kind: "fixed", month: 10, day: 1 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["เลื่อนขั้นเงินเดือนครู รอบ 2"],
    contentIdeas: ["คู่มือเตรียมเอกสารเลื่อนขั้นเงินเดือน รอบ 2"],
  },
  {
    id: "probation-teacher-eval",
    title: "ประเมินครูผู้ช่วย",
    category: "evaluation",
    occurrence: { kind: "range", startMonth: 3, startDay: 1, endMonth: 3, endDay: 31 },
    precision: "approx",
    leadDays: 14,
    note: "ประเมินทุก 6 เดือน วันจริงขึ้นกับวันบรรจุของแต่ละคน ช่วงนี้เป็นตัวอย่างรอบหนึ่ง",
    searchTerms: ["ประเมินครูผู้ช่วย", "แบบประเมินครูผู้ช่วย"],
    contentIdeas: ["คู่มือเตรียมตัวประเมินครูผู้ช่วย"],
  },

  // ---- exam ----
  {
    id: "rt-p1",
    title: "สอบ RT ป.1",
    category: "exam",
    occurrence: { kind: "range", startMonth: 2, startDay: 1, endMonth: 2, endDay: 28 },
    precision: "approx",
    leadDays: 21,
    note: "วันสอบจริงประกาศโดย สทศ./สพฐ. เช็คประกาศทางการก่อนเผยแพร่กำหนดวันแน่นอน",
    searchTerms: ["ข้อสอบ RT ป.1", "แนวข้อสอบ RT"],
    contentIdeas: ["แนวข้อสอบ RT ป.1 พร้อมเฉลย", "เทคนิคเตรียมสอบ RT"],
  },
  {
    id: "nt-p3",
    title: "สอบ NT ป.3",
    category: "exam",
    occurrence: { kind: "range", startMonth: 3, startDay: 1, endMonth: 3, endDay: 31 },
    precision: "approx",
    leadDays: 21,
    note: "วันสอบจริงประกาศโดย สทศ./สพฐ. เช็คประกาศทางการก่อนเผยแพร่กำหนดวันแน่นอน",
    searchTerms: ["ข้อสอบ NT ป.3", "แนวข้อสอบ NT"],
    contentIdeas: ["แนวข้อสอบ NT ป.3 พร้อมเฉลย"],
  },
  {
    id: "onet-p6",
    title: "สอบ O-NET ป.6",
    category: "exam",
    occurrence: { kind: "range", startMonth: 2, startDay: 1, endMonth: 2, endDay: 28 },
    precision: "approx",
    leadDays: 21,
    note: "วันสอบจริงประกาศโดย สทศ. เช็คประกาศทางการก่อนเผยแพร่กำหนดวันแน่นอน",
    searchTerms: ["ข้อสอบ O-NET ป.6", "แนวข้อสอบ O-NET ป.6"],
    contentIdeas: ["แนวข้อสอบ O-NET ป.6 พร้อมเฉลย"],
  },
  {
    id: "onet-m3",
    title: "สอบ O-NET ม.3",
    category: "exam",
    occurrence: { kind: "range", startMonth: 2, startDay: 1, endMonth: 2, endDay: 28 },
    precision: "approx",
    leadDays: 21,
    note: "วันสอบจริงประกาศโดย สทศ. เช็คประกาศทางการก่อนเผยแพร่กำหนดวันแน่นอน",
    searchTerms: ["ข้อสอบ O-NET ม.3"],
    contentIdeas: ["แนวข้อสอบ O-NET ม.3 พร้อมเฉลย"],
  },
  {
    id: "onet-m6",
    title: "สอบ O-NET ม.6",
    category: "exam",
    occurrence: { kind: "range", startMonth: 3, startDay: 1, endMonth: 3, endDay: 15 },
    precision: "approx",
    leadDays: 21,
    note: "วันสอบจริงประกาศโดย สทศ. เช็คประกาศทางการก่อนเผยแพร่กำหนดวันแน่นอน",
    searchTerms: ["ข้อสอบ O-NET ม.6"],
    contentIdeas: ["แนวข้อสอบ O-NET ม.6 พร้อมเฉลย"],
  },
  {
    id: "midterm-term-1",
    title: "สอบกลางภาคเรียนที่ 1",
    category: "exam",
    occurrence: { kind: "range", startMonth: 7, startDay: 15, endMonth: 8, endDay: 15 },
    precision: "approx",
    leadDays: 14,
    note: "วันสอบขึ้นกับปฏิทินวิชาการของแต่ละโรงเรียน",
    searchTerms: ["ข้อสอบกลางภาค", "แนวข้อสอบกลางภาค"],
    contentIdeas: ["แบบทดสอบกลางภาคพร้อมเฉลย"],
  },
  {
    id: "final-term-1",
    title: "สอบปลายภาคเรียนที่ 1",
    category: "exam",
    occurrence: { kind: "range", startMonth: 9, startDay: 15, endMonth: 10, endDay: 10 },
    precision: "approx",
    leadDays: 14,
    note: "วันสอบขึ้นกับปฏิทินวิชาการของแต่ละโรงเรียน",
    searchTerms: ["ข้อสอบปลายภาค เทอม 1"],
    contentIdeas: ["แบบทดสอบปลายภาคเทอม 1 พร้อมเฉลย"],
  },
  {
    id: "midterm-term-2",
    title: "สอบกลางภาคเรียนที่ 2",
    category: "exam",
    occurrence: { kind: "range", startMonth: 12, startDay: 15, endMonth: 1, endDay: 15 },
    precision: "approx",
    leadDays: 14,
    note: "วันสอบขึ้นกับปฏิทินวิชาการของแต่ละโรงเรียน",
    searchTerms: ["ข้อสอบกลางภาค เทอม 2"],
    contentIdeas: ["แบบทดสอบกลางภาคเทอม 2 พร้อมเฉลย"],
  },
  {
    id: "final-term-2",
    title: "สอบปลายภาคเรียนที่ 2",
    category: "exam",
    occurrence: { kind: "range", startMonth: 2, startDay: 15, endMonth: 3, endDay: 10 },
    precision: "approx",
    leadDays: 14,
    note: "วันสอบขึ้นกับปฏิทินวิชาการของแต่ละโรงเรียน",
    searchTerms: ["ข้อสอบปลายภาค เทอม 2"],
    contentIdeas: ["แบบทดสอบปลายภาคเทอม 2 พร้อมเฉลย"],
  },

  // ---- competition ----
  {
    id: "sillapa-regional",
    title: "งานศิลปหัตถกรรมนักเรียน ระดับเขตพื้นที่",
    category: "competition",
    occurrence: { kind: "range", startMonth: 8, startDay: 15, endMonth: 9, endDay: 30 },
    precision: "approx",
    leadDays: 21,
    note: "วันแข่งขันจริงประกาศโดยเขตพื้นที่การศึกษาแต่ละเขต",
    searchTerms: ["ศิลปหัตถกรรมนักเรียน", "เกณฑ์การแข่งขันศิลปหัตถกรรม"],
    contentIdeas: ["สรุปเกณฑ์การแข่งขันศิลปหัตถกรรมปีนี้", "ไอเดียเตรียมทีมแข่งขัน"],
  },
  {
    id: "sillapa-national",
    title: "งานศิลปหัตถกรรมนักเรียน ระดับชาติ",
    category: "competition",
    occurrence: { kind: "range", startMonth: 12, startDay: 1, endMonth: 2, endDay: 15 },
    precision: "approx",
    leadDays: 21,
    note: "วันแข่งขันจริงประกาศโดย สพฐ. ช่วงนี้เป็นค่าประมาณจากปีก่อนหน้า",
    searchTerms: ["ศิลปหัตถกรรมนักเรียนระดับชาติ"],
    contentIdeas: ["สรุปผลศิลปหัตถกรรมระดับชาติ"],
  },

  // ---- career ----
  {
    id: "teacher-recruitment-exam",
    title: "สอบครูผู้ช่วย รอบทั่วไป",
    category: "career",
    occurrence: { kind: "range", startMonth: 5, startDay: 1, endMonth: 7, endDay: 31 },
    precision: "approx",
    leadDays: 30,
    note: "วันประกาศรับสมัครและสอบเปลี่ยนทุกปี เช็คประกาศจาก ก.ค.ศ. และเขตพื้นที่",
    searchTerms: ["สอบครูผู้ช่วย", "แนวข้อสอบครูผู้ช่วย", "ประกาศสอบครูผู้ช่วย"],
    contentIdeas: ["แนวข้อสอบครูผู้ช่วยวิชาเอก", "สรุปขั้นตอนสมัครสอบครูผู้ช่วย"],
  },
  {
    id: "civil-service-exam",
    title: "สอบ ก.พ. ภาค ก",
    category: "career",
    occurrence: { kind: "range", startMonth: 3, startDay: 1, endMonth: 5, endDay: 31 },
    precision: "approx",
    leadDays: 30,
    note: "วันสอบเปลี่ยนทุกปี เช็คประกาศจากสำนักงาน ก.พ.",
    searchTerms: ["สอบ ก.พ. ภาค ก", "แนวข้อสอบ ก.พ."],
    contentIdeas: ["แนวข้อสอบ ก.พ. ภาค ก พร้อมเฉลย"],
  },
  {
    id: "teaching-license-renewal",
    title: "ต่ออายุใบประกอบวิชาชีพครู",
    category: "career",
    occurrence: { kind: "range", startMonth: 1, startDay: 1, endMonth: 12, endDay: 31 },
    precision: "approx",
    leadDays: 60,
    note: "วันหมดอายุขึ้นกับใบอนุญาตของแต่ละคน นี่คือคอนเทนต์ที่มีดีมานด์ตลอดปี ไม่ผูกกับเดือนใดเดือนหนึ่ง",
    searchTerms: ["ต่อใบประกอบวิชาชีพครู", "ขั้นตอนต่อใบอนุญาตประกอบวิชาชีพ"],
    contentIdeas: ["คู่มือต่อใบประกอบวิชาชีพครูทีละขั้นตอน"],
  },

  // ---- term ----
  {
    id: "term-1-open",
    title: "เปิดภาคเรียนที่ 1",
    category: "term",
    occurrence: { kind: "fixed", month: 5, day: 16 },
    precision: "exact",
    leadDays: 14,
    searchTerms: ["เปิดเทอม 1", "เตรียมตัวเปิดเทอม"],
    contentIdeas: ["เช็คลิสต์เตรียมตัวเปิดเทอม", "ไอเดียกิจกรรมปฐมนิเทศ"],
  },
  {
    id: "term-1-close",
    title: "ปิดภาคเรียนที่ 1",
    category: "term",
    occurrence: { kind: "range", startMonth: 10, startDay: 1, endMonth: 10, endDay: 31 },
    precision: "approx",
    leadDays: 14,
    note: "วันปิดเทอมต่างกันในแต่ละโรงเรียน",
    searchTerms: ["ปิดเทอม 1"],
    contentIdeas: ["กิจกรรมช่วงปิดเทอม"],
  },
  {
    id: "term-2-open",
    title: "เปิดภาคเรียนที่ 2",
    category: "term",
    occurrence: { kind: "range", startMonth: 11, startDay: 1, endMonth: 11, endDay: 15 },
    precision: "approx",
    leadDays: 14,
    note: "วันเปิดเทอมต่างกันในแต่ละโรงเรียน",
    searchTerms: ["เปิดเทอม 2"],
    contentIdeas: ["เช็คลิสต์เตรียมตัวเปิดเทอม 2"],
  },
  {
    id: "term-2-close",
    title: "ปิดภาคเรียนใหญ่",
    category: "term",
    occurrence: { kind: "range", startMonth: 4, startDay: 1, endMonth: 4, endDay: 30 },
    precision: "approx",
    leadDays: 14,
    note: "วันปิดเทอมต่างกันในแต่ละโรงเรียน",
    searchTerms: ["ปิดเทอมใหญ่", "กิจกรรมปิดเทอมภาคฤดูร้อน"],
    contentIdeas: ["ไอเดียกิจกรรมปิดเทอมภาคฤดูร้อน"],
  },
];
